on:
    push:
        branches:
        - mnt
name: Deploy spacedeck prod

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@master
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS_PROD }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER_PROD }}
            username: ${{ secrets.REGISTRY_USERNAME_PROD }}
            password: ${{ secrets.REGISTRY_PASSWORD_PROD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER_PROD }}/spacedeck-open:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER_PROD }}/spacedeck-open:${{ github.sha }}
            
        - name: 'Deploy to Azure App Service'
          uses: 'azure/webapps-deploy@v2'
          with:
            app-name: 'meetingmaker-spacedeck'
            images: ${{ secrets.REGISTRY_LOGIN_SERVER_PROD }}/spacedeck-open:${{ github.sha }}

    
